modLoader = "javafml"
loaderVersion = "[31,)"
[[mods]]
modId = "mc_unit_example"
version = "${file.jarVersion}"
displayName = "MCUnit Example Mod"
logoFile = "logo-mc-unit-example.png"
credits = ""
authors = "AterAnimAvis"
description = '''
An Example Mod
'''
